"""Service layer helpers for the active Streamlit app surface."""

from src.services.channel_idea_service import ChannelIdeaBundle, IdeaSuggestion, ThemeRecommendation, build_grounded_idea_bundle, maybe_generate_ai_overlay
from src.services.channel_insights_service import (
    TOPIC_MODE_BERTOPIC_OPTIONAL,
    TOPIC_MODE_HEURISTIC,
    list_connected_channels,
    load_channel_insights,
    refresh_channel_insights,
)
from src.services.channel_snapshot_store import (
    DEFAULT_CHANNEL_INSIGHTS_DB,
    get_tracked_channel,
    initialize_channel_snapshot_store,
    list_channel_snapshot_history,
    list_tracked_channels,
    load_latest_channel_snapshot,
    store_channel_snapshot,
    upsert_tracked_channel,
)
from src.services.model_artifact_service import (
    MODEL_TYPE_BERTOPIC_GLOBAL,
    ModelArtifactManifest,
    ModelArtifactStatus,
    ensure_bertopic_artifact_ready,
    fetch_bertopic_manifest,
    get_bertopic_artifact_status,
    get_model_artifact_manifest_url,
    model_artifacts_enabled,
)
from src.services.outlier_ai import InsightCard, OutlierAIReport, generate_outlier_ai_report
from src.services.outliers_finder import (
    ChannelBaseline,
    DURATION_BUCKETS,
    OutlierCandidate,
    OutlierSearchRequest,
    OutlierSearchResult,
    build_age_bucket_summary,
    build_duration_summary,
    build_scan_quality_summary,
    build_title_keyword_summary,
    build_title_pattern_summary,
    score_band_for_value,
    search_outlier_videos,
)
from src.services.public_channel_service import PublicChannelWorkspace, ensure_public_channel_frame, load_public_channel_workspace
from src.services.thumbnail_hub_service import PreparedThumbnailArtifact, ThumbnailPreview, prepare_thumbnail_download, preview_thumbnail_target, resolve_video_target
from src.services.topic_analysis_service import (
    add_channel_video_features,
    assign_topic_labels,
    build_duration_metrics,
    build_publish_day_metrics,
    build_publish_hour_metrics,
    build_title_pattern_metrics,
    build_topic_metrics,
    classify_title_pattern,
    duration_bucket,
    normalize_topic_token,
    tokenize_topic_text,
)
from src.services.topic_model_runtime import TopicModelInferenceResult, apply_optional_topic_model, build_bertopic_inference_text

__all__ = [
    "ChannelIdeaBundle",
    "IdeaSuggestion",
    "ThemeRecommendation",
    "build_grounded_idea_bundle",
    "maybe_generate_ai_overlay",
    "TOPIC_MODE_HEURISTIC",
    "TOPIC_MODE_BERTOPIC_OPTIONAL",
    "list_connected_channels",
    "load_channel_insights",
    "refresh_channel_insights",
    "DEFAULT_CHANNEL_INSIGHTS_DB",
    "get_tracked_channel",
    "initialize_channel_snapshot_store",
    "list_channel_snapshot_history",
    "list_tracked_channels",
    "load_latest_channel_snapshot",
    "store_channel_snapshot",
    "upsert_tracked_channel",
    "MODEL_TYPE_BERTOPIC_GLOBAL",
    "ModelArtifactManifest",
    "ModelArtifactStatus",
    "ensure_bertopic_artifact_ready",
    "fetch_bertopic_manifest",
    "get_bertopic_artifact_status",
    "get_model_artifact_manifest_url",
    "model_artifacts_enabled",
    "InsightCard",
    "OutlierAIReport",
    "generate_outlier_ai_report",
    "ChannelBaseline",
    "DURATION_BUCKETS",
    "OutlierCandidate",
    "OutlierSearchRequest",
    "OutlierSearchResult",
    "build_age_bucket_summary",
    "build_duration_summary",
    "build_scan_quality_summary",
    "build_title_keyword_summary",
    "build_title_pattern_summary",
    "score_band_for_value",
    "search_outlier_videos",
    "PublicChannelWorkspace",
    "ensure_public_channel_frame",
    "load_public_channel_workspace",
    "PreparedThumbnailArtifact",
    "ThumbnailPreview",
    "prepare_thumbnail_download",
    "preview_thumbnail_target",
    "resolve_video_target",
    "add_channel_video_features",
    "assign_topic_labels",
    "build_duration_metrics",
    "build_publish_day_metrics",
    "build_publish_hour_metrics",
    "build_title_pattern_metrics",
    "build_topic_metrics",
    "classify_title_pattern",
    "duration_bucket",
    "normalize_topic_token",
    "tokenize_topic_text",
    "TopicModelInferenceResult",
    "apply_optional_topic_model",
    "build_bertopic_inference_text",
]
